/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CaseStudyResult = IDL.Record({
  'metric' : IDL.Text,
  'description' : IDL.Text,
});
export const CreateCaseStudyInput = IDL.Record({
  'title' : IDL.Text,
  'tools' : IDL.Vec(IDL.Text),
  'clientType' : IDL.Text,
  'keyMetricLabel' : IDL.Text,
  'results' : IDL.Vec(CaseStudyResult),
  'iconName' : IDL.Text,
  'approach' : IDL.Text,
  'keyMetric' : IDL.Text,
  'problem' : IDL.Text,
  'industry' : IDL.Text,
});
export const CaseStudyId = IDL.Nat;
export const CreateCaseStudyResult = IDL.Variant({
  'ok' : CaseStudyId,
  'err' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CaseStudy = IDL.Record({
  'id' : CaseStudyId,
  'title' : IDL.Text,
  'tools' : IDL.Vec(IDL.Text),
  'clientType' : IDL.Text,
  'createdAt' : Timestamp,
  'keyMetricLabel' : IDL.Text,
  'results' : IDL.Vec(CaseStudyResult),
  'iconName' : IDL.Text,
  'updatedAt' : Timestamp,
  'approach' : IDL.Text,
  'keyMetric' : IDL.Text,
  'problem' : IDL.Text,
  'industry' : IDL.Text,
});
export const ServiceInterest = IDL.Variant({
  'other' : IDL.Null,
  'dataExtraction' : IDL.Null,
  'aiAnalytics' : IDL.Null,
  'dataEngineering' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
});
export const SubmitContactInput = IDL.Record({
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
});
export const ContactId = IDL.Nat;
export const SubmitContactResult = IDL.Variant({
  'ok' : ContactId,
  'err' : IDL.Text,
});
export const UpdateCaseStudyInput = IDL.Record({
  'title' : IDL.Text,
  'tools' : IDL.Vec(IDL.Text),
  'clientType' : IDL.Text,
  'keyMetricLabel' : IDL.Text,
  'results' : IDL.Vec(CaseStudyResult),
  'iconName' : IDL.Text,
  'approach' : IDL.Text,
  'keyMetric' : IDL.Text,
  'problem' : IDL.Text,
  'industry' : IDL.Text,
});
export const UpdateCaseStudyResult = IDL.Variant({
  'ok' : CaseStudy,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCaseStudy' : IDL.Func(
      [CreateCaseStudyInput],
      [CreateCaseStudyResult],
      [],
    ),
  'deleteCaseStudy' : IDL.Func([CaseStudyId], [IDL.Bool], []),
  'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseStudyById' : IDL.Func([CaseStudyId], [IDL.Opt(CaseStudy)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContactForm' : IDL.Func(
      [SubmitContactInput],
      [SubmitContactResult],
      [],
    ),
  'updateCaseStudy' : IDL.Func(
      [CaseStudyId, UpdateCaseStudyInput],
      [UpdateCaseStudyResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CaseStudyResult = IDL.Record({
    'metric' : IDL.Text,
    'description' : IDL.Text,
  });
  const CreateCaseStudyInput = IDL.Record({
    'title' : IDL.Text,
    'tools' : IDL.Vec(IDL.Text),
    'clientType' : IDL.Text,
    'keyMetricLabel' : IDL.Text,
    'results' : IDL.Vec(CaseStudyResult),
    'iconName' : IDL.Text,
    'approach' : IDL.Text,
    'keyMetric' : IDL.Text,
    'problem' : IDL.Text,
    'industry' : IDL.Text,
  });
  const CaseStudyId = IDL.Nat;
  const CreateCaseStudyResult = IDL.Variant({
    'ok' : CaseStudyId,
    'err' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CaseStudy = IDL.Record({
    'id' : CaseStudyId,
    'title' : IDL.Text,
    'tools' : IDL.Vec(IDL.Text),
    'clientType' : IDL.Text,
    'createdAt' : Timestamp,
    'keyMetricLabel' : IDL.Text,
    'results' : IDL.Vec(CaseStudyResult),
    'iconName' : IDL.Text,
    'updatedAt' : Timestamp,
    'approach' : IDL.Text,
    'keyMetric' : IDL.Text,
    'problem' : IDL.Text,
    'industry' : IDL.Text,
  });
  const ServiceInterest = IDL.Variant({
    'other' : IDL.Null,
    'dataExtraction' : IDL.Null,
    'aiAnalytics' : IDL.Null,
    'dataEngineering' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
  });
  const SubmitContactInput = IDL.Record({
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
  });
  const ContactId = IDL.Nat;
  const SubmitContactResult = IDL.Variant({
    'ok' : ContactId,
    'err' : IDL.Text,
  });
  const UpdateCaseStudyInput = IDL.Record({
    'title' : IDL.Text,
    'tools' : IDL.Vec(IDL.Text),
    'clientType' : IDL.Text,
    'keyMetricLabel' : IDL.Text,
    'results' : IDL.Vec(CaseStudyResult),
    'iconName' : IDL.Text,
    'approach' : IDL.Text,
    'keyMetric' : IDL.Text,
    'problem' : IDL.Text,
    'industry' : IDL.Text,
  });
  const UpdateCaseStudyResult = IDL.Variant({
    'ok' : CaseStudy,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCaseStudy' : IDL.Func(
        [CreateCaseStudyInput],
        [CreateCaseStudyResult],
        [],
      ),
    'deleteCaseStudy' : IDL.Func([CaseStudyId], [IDL.Bool], []),
    'getAllCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseStudyById' : IDL.Func(
        [CaseStudyId],
        [IDL.Opt(CaseStudy)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContactForm' : IDL.Func(
        [SubmitContactInput],
        [SubmitContactResult],
        [],
      ),
    'updateCaseStudy' : IDL.Func(
        [CaseStudyId, UpdateCaseStudyInput],
        [UpdateCaseStudyResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };