/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseStudy {
  'id' : CaseStudyId,
  'title' : string,
  'tools' : Array<string>,
  'clientType' : string,
  'createdAt' : Timestamp,
  'keyMetricLabel' : string,
  'results' : Array<CaseStudyResult>,
  'iconName' : string,
  'updatedAt' : Timestamp,
  'approach' : string,
  'keyMetric' : string,
  'problem' : string,
  'industry' : string,
}
export type CaseStudyId = bigint;
export interface CaseStudyResult { 'metric' : string, 'description' : string }
export type ContactId = bigint;
export interface ContactSubmission {
  'id' : bigint,
  'projectDescription' : string,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'serviceInterest' : ServiceInterest,
}
export interface CreateCaseStudyInput {
  'title' : string,
  'tools' : Array<string>,
  'clientType' : string,
  'keyMetricLabel' : string,
  'results' : Array<CaseStudyResult>,
  'iconName' : string,
  'approach' : string,
  'keyMetric' : string,
  'problem' : string,
  'industry' : string,
}
export type CreateCaseStudyResult = { 'ok' : CaseStudyId } |
  { 'err' : string };
export type ServiceInterest = { 'other' : null } |
  { 'dataExtraction' : null } |
  { 'aiAnalytics' : null } |
  { 'dataEngineering' : null };
export interface SubmitContactInput {
  'projectDescription' : string,
  'name' : string,
  'email' : string,
  'serviceInterest' : ServiceInterest,
}
export type SubmitContactResult = { 'ok' : ContactId } |
  { 'err' : string };
export type Timestamp = bigint;
export interface UpdateCaseStudyInput {
  'title' : string,
  'tools' : Array<string>,
  'clientType' : string,
  'keyMetricLabel' : string,
  'results' : Array<CaseStudyResult>,
  'iconName' : string,
  'approach' : string,
  'keyMetric' : string,
  'problem' : string,
  'industry' : string,
}
export type UpdateCaseStudyResult = { 'ok' : CaseStudy } |
  { 'err' : string };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCaseStudy' : ActorMethod<
    [CreateCaseStudyInput],
    CreateCaseStudyResult
  >,
  'deleteCaseStudy' : ActorMethod<[CaseStudyId], boolean>,
  'getAllCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseStudyById' : ActorMethod<[CaseStudyId], [] | [CaseStudy]>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitContactForm' : ActorMethod<[SubmitContactInput], SubmitContactResult>,
  'updateCaseStudy' : ActorMethod<
    [CaseStudyId, UpdateCaseStudyInput],
    UpdateCaseStudyResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];