/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CreateCaseStudyResult = {
    __kind__: "ok";
    ok: CaseStudyId;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export type CaseStudyId = bigint;
export interface ContactSubmission {
    id: bigint;
    projectDescription: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    serviceInterest: ServiceInterest;
}
export type SubmitContactResult = {
    __kind__: "ok";
    ok: ContactId;
} | {
    __kind__: "err";
    err: string;
};
export interface CaseStudy {
    id: CaseStudyId;
    title: string;
    tools: Array<string>;
    clientType: string;
    createdAt: Timestamp;
    keyMetricLabel: string;
    results: Array<CaseStudyResult>;
    iconName: string;
    updatedAt: Timestamp;
    approach: string;
    keyMetric: string;
    problem: string;
    industry: string;
}
export type UpdateCaseStudyResult = {
    __kind__: "ok";
    ok: CaseStudy;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateCaseStudyInput {
    title: string;
    tools: Array<string>;
    clientType: string;
    keyMetricLabel: string;
    results: Array<CaseStudyResult>;
    iconName: string;
    approach: string;
    keyMetric: string;
    problem: string;
    industry: string;
}
export type ContactId = bigint;
export interface SubmitContactInput {
    projectDescription: string;
    name: string;
    email: string;
    serviceInterest: ServiceInterest;
}
export interface CaseStudyResult {
    metric: string;
    description: string;
}
export interface CreateCaseStudyInput {
    title: string;
    tools: Array<string>;
    clientType: string;
    keyMetricLabel: string;
    results: Array<CaseStudyResult>;
    iconName: string;
    approach: string;
    keyMetric: string;
    problem: string;
    industry: string;
}
export enum ServiceInterest {
    other = "other",
    dataExtraction = "dataExtraction",
    aiAnalytics = "aiAnalytics",
    dataEngineering = "dataEngineering"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCaseStudy(input: CreateCaseStudyInput): Promise<CreateCaseStudyResult>;
    deleteCaseStudy(id: CaseStudyId): Promise<boolean>;
    getAllCaseStudies(): Promise<Array<CaseStudy>>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseStudyById(id: CaseStudyId): Promise<CaseStudy | null>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    isCallerAdmin(): Promise<boolean>;
    submitContactForm(input: SubmitContactInput): Promise<SubmitContactResult>;
    updateCaseStudy(id: CaseStudyId, input: UpdateCaseStudyInput): Promise<UpdateCaseStudyResult>;
}
import type { CaseStudy as _CaseStudy, CaseStudyId as _CaseStudyId, ContactId as _ContactId, ContactSubmission as _ContactSubmission, CreateCaseStudyResult as _CreateCaseStudyResult, ServiceInterest as _ServiceInterest, SubmitContactInput as _SubmitContactInput, SubmitContactResult as _SubmitContactResult, Timestamp as _Timestamp, UpdateCaseStudyResult as _UpdateCaseStudyResult, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCaseStudy(arg0: CreateCaseStudyInput): Promise<CreateCaseStudyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createCaseStudy(arg0);
                return from_candid_CreateCaseStudyResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCaseStudy(arg0);
            return from_candid_CreateCaseStudyResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCaseStudy(arg0: CaseStudyId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCaseStudy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCaseStudy(arg0);
            return result;
        }
    }
    async getAllCaseStudies(): Promise<Array<CaseStudy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCaseStudies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCaseStudies();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseStudyById(arg0: CaseStudyId): Promise<CaseStudy | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseStudyById(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseStudyById(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async submitContactForm(arg0: SubmitContactInput): Promise<SubmitContactResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(to_candid_SubmitContactInput_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SubmitContactResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(to_candid_SubmitContactInput_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SubmitContactResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCaseStudy(arg0: CaseStudyId, arg1: UpdateCaseStudyInput): Promise<UpdateCaseStudyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaseStudy(arg0, arg1);
                return from_candid_UpdateCaseStudyResult_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaseStudy(arg0, arg1);
            return from_candid_UpdateCaseStudyResult_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContactSubmission_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactSubmission): ContactSubmission {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CreateCaseStudyResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateCaseStudyResult): CreateCaseStudyResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceInterest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceInterest): ServiceInterest {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitContactResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitContactResult): SubmitContactResult {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateCaseStudyResult_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateCaseStudyResult): UpdateCaseStudyResult {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseStudy]): CaseStudy | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    projectDescription: string;
    name: string;
    submittedAt: _Timestamp;
    email: string;
    serviceInterest: _ServiceInterest;
}): {
    id: bigint;
    projectDescription: string;
    name: string;
    submittedAt: Timestamp;
    email: string;
    serviceInterest: ServiceInterest;
} {
    return {
        id: value.id,
        projectDescription: value.projectDescription,
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        serviceInterest: from_candid_ServiceInterest_n11(_uploadFile, _downloadFile, value.serviceInterest)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    dataExtraction: null;
} | {
    aiAnalytics: null;
} | {
    dataEngineering: null;
}): ServiceInterest {
    return "other" in value ? ServiceInterest.other : "dataExtraction" in value ? ServiceInterest.dataExtraction : "aiAnalytics" in value ? ServiceInterest.aiAnalytics : "dataEngineering" in value ? ServiceInterest.dataEngineering : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ContactId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ContactId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CaseStudy;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CaseStudy;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CaseStudyId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CaseStudyId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactSubmission>): Array<ContactSubmission> {
    return value.map((x)=>from_candid_ContactSubmission_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceInterest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceInterest): _ServiceInterest {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitContactInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitContactInput): _SubmitContactInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectDescription: string;
    name: string;
    email: string;
    serviceInterest: ServiceInterest;
}): {
    projectDescription: string;
    name: string;
    email: string;
    serviceInterest: _ServiceInterest;
} {
    return {
        projectDescription: value.projectDescription,
        name: value.name,
        email: value.email,
        serviceInterest: to_candid_ServiceInterest_n15(_uploadFile, _downloadFile, value.serviceInterest)
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceInterest): {
    other: null;
} | {
    dataExtraction: null;
} | {
    aiAnalytics: null;
} | {
    dataEngineering: null;
} {
    return value == ServiceInterest.other ? {
        other: null
    } : value == ServiceInterest.dataExtraction ? {
        dataExtraction: null
    } : value == ServiceInterest.aiAnalytics ? {
        aiAnalytics: null
    } : value == ServiceInterest.dataEngineering ? {
        dataEngineering: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
